name: latest

on:
  push:
    paths-ignore:
      - '*.md'
      - LICENSE
      - nginx/
      - postgres/

  workflow_dispatch:

env:
  BACKEND_DOCKER_BASE_NAME: ghcr.io/iamtakagi/twichat_backend
  WEB_DOCKER_BASE_NAME: ghcr.io/iamtakagi/twichat_web

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build & Push (twichat_backend)
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
        with:
          context: backend
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ env.BACKEND_DOCKER_BASE_NAME }}:latest
          cache-from: ${{ env.BACKEND_DOCKER_BASE_NAME }}:latest
          build-args: BUILDKIT_INLINE_CACHE=1

      - name: Build & Push (twichat_web)
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
        with:
          context: web
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ env.WEB_DOCKER_BASE_NAME }}:latest
          cache-from: ${{ env.WEB_DOCKER_BASE_NAME }}:latest
          build-args: BUILDKIT_INLINE_CACHE=1
      